#!/usr/bin/env python

import sys, os

testname = sys.argv[1]
simulator = "cver"

filelist = " -f env/tb.vf"
testdef  = " +incdir+env -l logs/%s.log +define+DUMPFILE_NAME=\\\"logs/%s.dump\\\" +define+PROGRAM_FILE=\\\"tests/%s.vmem\\\"" % (testname, testname, testname)

os.chdir ("tests")
os.system ("make %s.vmem" % testname)
os.chdir ("..")

command = simulator + filelist + testdef

print "command:",command
os.system (command)

